import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'src/features/auth/ui/screens/login_screen.dart';
import 'firebase_options.dart'; // auto-generated by Firebase CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const SweatSmartApp());
}

class SweatSmartApp extends StatelessWidget {
  const SweatSmartApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'SweatSmart',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const LoginScreen(),
    );
  }
}
